/*
 * @erisera-code/circuit/tokens — circuit's design tokens as data, plus a
 * function that renders them as namespaced (`--circuit-*`) CSS.
 *
 * For applications. Unlike tokens.css (generic `--bg`, `--accent`, ... on
 * :root, meant for sites that adopt circuit wholesale), nothing here can
 * collide with an app's own custom properties, and it is plain JS so a
 * JS-only import-map / vendor pipeline can inject it:
 *
 *   import { tokensCss } from '@erisera-code/circuit/tokens';
 *   const style = document.createElement('style');
 *   style.textContent = tokensCss();
 *   document.head.append(style);
 *
 * Values mirror tokens.css (a test enforces parity). Keys are unprefixed
 * role names; `--circuit-` is added when rendering CSS.
 */

export const PREFIX = 'circuit';

const hue = 'var(--circuit-hue)';

/** Mode-independent tokens (type, spacing, radius, motion, hue). */
const shared = {
  hue: '25',
  'shadow-accent': `0 6px 18px -4px hsl(${hue} 95% 46% / 0.35)`,
  'f-display': "'JetBrains Mono Variable', 'JetBrains Mono', 'SF Mono', monospace",
  'f-body': "'IBM Plex Sans Variable', 'IBM Plex Sans', system-ui, sans-serif",
  'f-mono': "'JetBrains Mono Variable', 'JetBrains Mono', 'SF Mono', monospace",
  'sp-1': '4px', 'sp-2': '8px', 'sp-3': '12px', 'sp-4': '16px', 'sp-5': '20px',
  'sp-6': '24px', 'sp-8': '32px', 'sp-10': '40px', 'sp-14': '56px', 'sp-20': '80px',
  'r-sm': '6px', r: '8px', 'r-lg': '12px', 'r-xl': '16px', 'r-2xl': '24px', 'r-full': '999px',
  't-fast': '150ms ease',
  't-base': '200ms ease',
};

const light = {
  bg: '#f8fafc',
  surface: '#ffffff',
  inset: '#f1f5f9',
  text: '#1e293b',
  dim: '#5b6b82',
  faint: '#94a3b8',
  border: '#e2e8f0',
  accent: `oklch(from hsl(${hue} 95% 46%) min(l, 0.52) c h)`,
  'accent-hover': `oklch(from hsl(${hue} 95% 40%) min(l, 0.47) c h)`,
  'accent-soft': `hsl(${hue} 95% 53% / 0.09)`,
  'accent-border': `hsl(${hue} 95% 46% / 0.35)`,
  success: '#0b7a4b', 'success-soft': '#0b7a4b14',
  warning: '#a45506', 'warning-soft': '#a4550614',
  danger: '#c4372b', 'danger-soft': '#c4372b14',
  info: '#1d6fbf', 'info-soft': '#1d6fbf14',
  scrim: 'rgba(15, 23, 42, 0.45)',
  'cat-1': '#2563eb', 'cat-2': '#0d9488', 'cat-3': '#7c3aed',
  'cat-4': '#db2777', 'cat-5': '#d97706', 'cat-6': '#65a30d',
  'code-bg': '#0f172a',
  'code-ink': '#e2e8f0',
  'sx-kw': '#d6337d', 'sx-str': '#0f9d63', 'sx-fn': '#1d6fbf', 'sx-cm': '#8b93a1',
  'sx-num': '#9333d6', 'sx-tag': '#b45f06', 'sx-attr': '#1d8f8f', 'sx-punct': '#94a3b8',
  'sx-type': '#7c4fd6', 'sx-bool': '#c0392b',
  'shadow-sm': '0 1px 2px rgba(15, 23, 42, 0.05)',
  'shadow-md': '0 4px 10px -2px rgba(15, 23, 42, 0.1)',
  'shadow-lg': '0 14px 32px -8px rgba(15, 23, 42, 0.16)',
};

const dark = {
  bg: '#0f172a',
  surface: '#16203a',
  inset: '#1e293b',
  text: '#e2e8f0',
  dim: '#94a3b8',
  faint: '#475569',
  border: '#334155',
  accent: `oklch(from hsl(${hue} 92% 58%) max(l, 0.71) c h)`,
  'accent-hover': `oklch(from hsl(${hue} 92% 66%) max(l, 0.76) c h)`,
  'accent-soft': `hsl(${hue} 92% 58% / 0.13)`,
  'accent-border': `hsl(${hue} 92% 58% / 0.4)`,
  success: '#3ecf8e', 'success-soft': '#3ecf8e17',
  warning: '#e0a84a', 'warning-soft': '#e0a84a17',
  danger: '#f0665a', 'danger-soft': '#f0665a17',
  info: '#5fa8e8', 'info-soft': '#5fa8e817',
  scrim: 'rgba(2, 6, 23, 0.65)',
  'cat-1': '#60a5fa', 'cat-2': '#2dd4bf', 'cat-3': '#a78bfa',
  'cat-4': '#f472b6', 'cat-5': '#fbbf24', 'cat-6': '#a3e635',
  'code-bg': '#0b1120',
  'code-ink': '#dbe3ef',
  'sx-kw': '#f472b6', 'sx-str': '#34d399', 'sx-fn': '#38bdf8', 'sx-cm': '#7e8aa0',
  'sx-num': '#c084fc', 'sx-tag': '#f0b35c', 'sx-attr': '#4fd1d1', 'sx-punct': '#475569',
  'sx-type': '#a78bfa', 'sx-bool': '#f16b5c',
  'shadow-sm': 'none',
  'shadow-md': '0 0 0 1px var(--circuit-border)',
  'shadow-lg': '0 0 0 1px var(--circuit-border), 0 20px 40px -12px rgba(0, 0, 0, 0.5)',
};

export const tokens = Object.freeze({
  shared: Object.freeze(shared),
  light: Object.freeze(light),
  dark: Object.freeze(dark),
});

const decls = (set, indent) =>
  Object.entries(set).map(([k, v]) => `${indent}--${PREFIX}-${k}: ${v};`).join('\n');

/**
 * Render the namespaced token CSS.
 *
 * Light is the default; dark applies when the OS prefers it (unless the page
 * opts into light with `data-theme="light"`), or explicitly with
 * `data-theme="dark"`. Every custom property is `--circuit-*`.
 *
 * @param {{ selector?: string }} [options] `selector` scopes the tokens to an
 *   element instead of `:root` (default `:root`).
 */
export function tokensCss({ selector = ':root' } = {}) {
  const isRoot = selector === ':root';
  const sys = isRoot ? `${selector}:not([data-theme='light'])` : selector;
  const on = (mode) => isRoot ? `[data-theme='${mode}']`
    : `[data-theme='${mode}'] ${selector},\n${selector}[data-theme='${mode}']`;
  return [
    `/* @erisera-code/circuit — namespaced app tokens (generated by tokensCss(); do not edit) */`,
    `${selector} {\n${decls(shared, '  ')}\n\n${decls(light, '  ')}\n}`,
    `@media (prefers-color-scheme: dark) {\n  ${sys} {\n${decls(dark, '    ')}\n  }\n}`,
    `${on('dark')} {\n${decls(dark, '  ')}\n}`,
    `${on('light')} {\n${decls(light, '  ')}\n}`,
  ].join('\n\n') + '\n';
}
